on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Build all scripts
        run: bun run build --all

      - name: Update builds repo
        run: |
          git config --global user.name "GitHub-Actions"
          git config --global user.email "actions@github.com"

          git clone https://GitHub-Actions:$TOKEN@github.com/Gimloader/builds.git builds-repo
          cd builds-repo

          cp -a ../build/libraries/. ./libraries/
          cp -a ../build/plugins/. ./plugins/

          git add -A
          git update-index --refresh
          git diff-index --quiet HEAD -- || (
            git commit -m "Update builds to https://github.com/Gimloader/client-plugins/commit/$GITHUB_SHA" &&
            git push
          )
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}